docker:
  image_name: fastapi-test-app
  tag: demo
google_cloud:
  project_id: inbound-coast-464901-f6
  region: northamerica-south1
artifact_registry:
  repository: fastapi-test-app
cloud_run:
  service: fastapi-test-app
